spring.application.name=proyecto-eapn-portabilidad

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/eapn}
spring.datasource.username=${DB_USER:eapn}
spring.datasource.password=${DB_PASSWORD:eapn_dev}
spring.sql.init.mode=never

spring.artemis.mode=native
spring.artemis.broker-url=${ARTEMIS_BROKER_URL:tcp://localhost:61616}
spring.artemis.user=${ARTEMIS_USER:eapn}
spring.artemis.password=${ARTEMIS_PASSWORD:eapn_dev}

app.wiremock.base-url=${WIREMOCK_BASE_URL:http://localhost:8081}
# Evitar reenvíos implícitos de notificaciones hasta definir una política de recuperación.
camel.component.http.automatic-retries-disabled=true
app.timezone=${APP_TIMEZONE:America/Asuncion}
spring.jackson.time-zone=${app.timezone}

camel.springboot.main-run-controller=true
